In [1]:
import numpy as np
a=np.array([0,1,2,3])

In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(10000)
%timeit [i**2 for i in l]

3.62 ms ± 624 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a=np.arange(10000)
%timeit a**2

9.7 µs ± 762 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
a=np.array([1,2,3,4,5,6])

In [7]:
a.ndim

1

In [8]:
a.shape ## you get a Tuple

(6,)

In [9]:
len(a)

6

In [10]:
b=np.array([[0,1,2],[3,4,5]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
len(b)#return size of 1 dimension

2

In [14]:
c=np.array([[[0,1],[2,3]],[[3,4],[5,6]]])

In [15]:
c.ndim

3

In [16]:
c.shape

(2, 2, 2)

In [17]:
c

array([[[0, 1],
        [2, 3]],

       [[3, 4],
        [5, 6]]])

In [18]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
a=np.arange(10)

In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b=np.arange(1,10,2)

In [22]:
b

array([1, 3, 5, 7, 9])

In [27]:
a=np.linspace(0,1,4)

In [28]:
a

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [29]:
a=np.linspace(0,1,6)#6 means 6 equal points in the range you provide

In [30]:
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [34]:
a=np.ones((2,2))#tuple contains(which inside the ones function) row and columns

In [35]:
a

array([[1., 1.],
       [1., 1.]])

In [36]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
a=np.eye(3)#identity Matrix

In [41]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [44]:
a=np.diag([1,2,3,4])#diagonal Matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [46]:
np.diag(a)#extract diagonal elements

array([1, 2, 3, 4])

In [51]:

a=np.random.rand(4)#uniform distributed Random Number
a

array([0.80645529, 0.70125592, 0.60570509, 0.7725964 ])

In [52]:

a=np.random.randn(4)#gaussian distributed Random Number
a

array([-0.61372191, -0.54439965,  0.22143037,  0.00358336])

In [53]:
a=np.arange(10)
a.dtype


dtype('int32')

In [54]:
a=np.arange(10,dtype="float64")
a.dtype

dtype('float64')

In [55]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
a=np.zeros((3,3))

In [57]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
a.dtype

dtype('float64')

In [59]:
d=np.array([1+2j,2+4j])
d.dtype

dtype('complex128')

In [60]:
d

array([1.+2.j, 2.+4.j])

In [61]:
b=np.array([True,False,True,False])
b.dtype

dtype('bool')

In [62]:
s=np.array(["kishore","Ramesh","KIlla"])

In [63]:
s.dtype

dtype('<U7')

In [64]:
a=np.arange(10)
a[5]

5

In [65]:
a=np.diag([1,2,3,4])
a[2,2]

3

In [68]:
a[2,1]=7 #assign value

In [69]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 7, 3, 0],
       [0, 0, 0, 4]])

In [70]:
a=np.arange(10)
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a[1:8:2]

array([1, 3, 5, 7])

In [84]:
a=np.arange(10)
a[5:]=10

In [85]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [86]:

b=np.arange(5)

In [87]:
a[5:]=b[::-1]

In [88]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [89]:
 a=np.arange(10)

In [90]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
b=a[::2]

In [92]:
b

array([0, 2, 4, 6, 8])

In [93]:
np.shares_memory(a,b)

True

In [95]:
b[0]=10

In [96]:
b

array([10,  2,  4,  6,  8])

In [97]:
a# a also modified 

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [98]:
a=np.arange(10)
c=a[::2].copy()

In [99]:
np.shares_memory(a,c)

False

In [100]:
c[0]

0

In [101]:
c[0]=10

In [102]:
c

array([10,  2,  4,  6,  8])

In [103]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a=np.random.randint(0,20,15) # 15 number from 0 to 20
a

array([16, 13,  8, 18, 16, 17, 15,  9, 13, 13,  2,  6,  8, 18, 14])

In [105]:
mask=(a%2==0)

In [106]:
a[mask]

array([16,  8, 18, 16,  2,  6,  8, 18, 14])

In [107]:
mask

array([ True, False,  True,  True,  True, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [108]:
a[mask]=0

In [109]:
a

array([ 0, 13,  0,  0,  0, 17, 15,  9, 13, 13,  0,  0,  0,  0,  0])

In [111]:
a=np.arange(0,100,10)

In [112]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [113]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [114]:
a[[9,7]]=-200

In [115]:
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Operations

In [116]:
a=np.array([1,2,3,4])

In [117]:
a

array([1, 2, 3, 4])

In [118]:
a+1

array([2, 3, 4, 5])

In [119]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

### arithmetic Operations are elementwise

In [120]:
b=np.ones(3)

In [122]:
b+1

array([2., 2., 2.])

In [123]:
b=np.ones(4)

In [126]:
b=b+1

In [129]:
a,b

(array([1, 2, 3, 4]), array([2., 2., 2., 2.]))

In [127]:
a-b#element wise subtraction

array([-1.,  0.,  1.,  2.])

In [128]:
a*b

array([2., 4., 6., 8.])

In [130]:
a=np.diag([1,2,3,4])

In [131]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [132]:
a*a#matrix Multiplication

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [133]:
a.dot(a) #matrix Multiplication

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [134]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])

In [135]:
a==b

array([False,  True, False,  True])

In [137]:
a>=b

array([False,  True,  True,  True])

In [139]:
#array-wise comparision
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

In [140]:
np.array_equal(a,c)

True

In [141]:
np.array_equal(a,b)

False

In [142]:
a=np.array([1,1,0.,0],dtype="bool")
b=np.array([1,0,1.,0],dtype="bool")

In [143]:
np.logical_and(a,b)

array([ True, False, False, False])

In [144]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [145]:
#transcendental

In [146]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [147]:
np.log(a)

C:\Users\prath\AppData\Local\Temp\ipykernel_17684\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [148]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [149]:
#shape mismatch
a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [150]:
#computing sum like reduce functions

In [151]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [152]:
x=np.array([[1,2],[3,4]])

In [153]:
x

array([[1, 2],
       [3, 4]])

In [154]:
x.sum(axis=0)#column 

array([4, 6])

In [156]:
x.sum(axis=1)#row

array([3, 7])

In [157]:
x=np.array([1,3,2])
x.min()

1

In [158]:
x.max()

3

In [159]:
x.argmax()#argument as index

1

In [160]:
x.argmin()

0

In [161]:
np.all([True,True,False])#logical AND

False

In [163]:
np.any([True,True,False])#logical OR

True

In [164]:
a=np.zeros((50,50))
np.any(a!=0)

False

In [165]:
np.all(a==a)

True

In [166]:
#array-wise comparision
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])

In [169]:
((a<=b) & (b<=c)).all()

True

In [171]:
a

array([1, 2, 3, 1])

In [170]:
a=np.array([1,2,3,1])
b=np.array([[1,2,3],[5,6,1]])

In [172]:

np.median(a)

1.5

In [173]:
a.mean()

1.75

In [177]:
a.std()

0.82915619758885

In [176]:
np.median(b,axis=-1)#axis=0 means columns and axis=1 means rows -1 means last axis

array([2., 5.])

In [ ]:
np.loadtxt()# to read text and convert to numpy array object

In [ ]:
data[:,1:]#take all rows but start from 1 st column to last

### Broadcasting

In [187]:
a=np.tile(np.arange(0,40,10),(3,1))

In [188]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [189]:
a1=a.T

In [190]:
a1

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [191]:
b=np.array([1,2,3,4])

In [192]:
b

array([1, 2, 3, 4])

In [193]:
a+b

array([[ 1, 12, 23, 34],
       [ 1, 12, 23, 34],
       [ 1, 12, 23, 34]])

In [194]:
a=np.arange(0,40,10)
a.shape

(4,)

In [195]:
a=a[:,np.newaxis]#add new axis -> 2D Array

In [196]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [197]:
a.shape

(4, 1)

In [198]:
a+b

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [199]:
#array Manipulation

In [200]:
a=np.array([[1,2,3],[4,5,6]])

In [202]:
a.ravel() #return continuous Flatten Array

array([1, 2, 3, 4, 5, 6])

In [203]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [204]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [205]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [206]:
a.shape

(2, 3)

In [207]:
b=a.ravel()

In [208]:
b

array([1, 2, 3, 4, 5, 6])

In [209]:
b=b.reshape((2,3))

In [210]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [211]:
b[0,0]=100

In [212]:
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [213]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [214]:
a=np.zeros((3,2))

In [215]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [218]:
b=a.T.reshape(3*2)

In [219]:
b[0]=100

In [220]:
b

array([100.,   0.,   0.,   0.,   0.,   0.])

In [221]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [224]:
a=np.arange(4*3*2).reshape(4,3,2)

In [225]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [226]:
a.shape

(4, 3, 2)

In [227]:
a[0,2,1]

5

In [228]:
#resizing issues

In [232]:
a=np.arange(4)

In [233]:
a.resize((8,))

In [234]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [235]:
b=a

In [236]:
b

array([0, 1, 2, 3, 0, 0, 0, 0])

In [237]:
a.resize((8,))

In [238]:
b.resize((8,))

In [239]:
a=np.array([[5,4,6],[2,3,2]])

In [242]:
np.sort(a,axis=0)#column wise sort

array([[2, 3, 2],
       [5, 4, 6]])

In [244]:
np.sort(a,axis=1)#row wise sort

array([[4, 5, 6],
       [2, 2, 3]])

In [245]:
a.sort()

In [246]:
a#inplace sort

array([[4, 5, 6],
       [2, 2, 3]])

In [248]:
a=np.array([4,3,1,2])

In [249]:
a

array([4, 3, 1, 2])

In [251]:
k=np.argsort(a)

In [252]:
k#got indices of sorted array

array([2, 3, 1, 0], dtype=int64)

In [253]:
a[k]# to get sorted numbers

array([1, 2, 3, 4])